version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb

  mongodb:
    build: ./database
    ports:
      - "27017:27017"